### ISSUE TITLE
Different Unusual Human Activity

### ISSUE THREAD

**Issue by sasin07** [Poornav/Unusual-Human-Activity-Detection#1]
Can I recognize multiple Unusual Human Activities using this project?

**Comment by Poornav** [comment]
Hi Sasin,

You can certainly do that but you need to have proper training dataset.

Regards,
Poornav

**Comment by sowmiya86** [comment]
can you help me out to clear this error?
Traceback (most recent call last):
  File "training.py", line 31, in <module>
    train_from_video(video)
  File "training.py", line 12, in train_from_video
    MotionInfOfFrames, rows, cols = mig.getMotionInfuenceMap(vid)
  File "/data/Unusual-Human-Activity-Detection/code/motionInfuenceGenerator.py", line 63, in getMotionInfuenceMap
    rows, cols = frame1.shape[0], frame1.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by DVLVD** [comment]
> can you help me out to clear this error?
> Traceback (most recent call last):
> File "training.py", line 31, in 
> train_from_video(video)
> File "training.py", line 12, in train_from_video
> MotionInfOfFrames, rows, cols = mig.getMotionInfuenceMap(vid)
> File "/data/Unusual-Human-Activity-Detection/code/motionInfuenceGenerator.py", line 63, in getMotionInfuenceMap
> rows, cols = frame1.shape[0], frame1.shape[1]
> AttributeError: 'NoneType' object has no attribute 'shape'

You need to put the whole path of the video, it's not getting the frame1 from the video.

if it still persists, put an r before the string : 

videopath = [r"C:\YOURPATH\Dataset\videos\scene1\YOURVIDEO.AVI"]

Do the path thing with all paths or try to configure your IDE to recognize where is the home folder.

**Comment by sofianishath** [comment]
hi 
i am getting the following error after running the code even after adding r in front of the path
Traceback (most recent call last):
  File "training.py", line 31, in <module>
    train_from_video(video)
  File "training.py", line 12, in train_from_video
    MotionInfoOfFrames, rows, cols = mig.getMotionInfuenceMap(vid)
  File "C:\Users\sofia\Anomaly_detection_poornav\motionInfuenceGenerator.py", line 98, in getMotionInfuenceMap
    opFlowOfBlocks,noOfRowInBlock,noOfColInBlock,blockSize,centreOfBlocks,xBlockSize,yBlockSize = roi.calcOptFlowOfBlocks(mag, ang,                                                                                                                 next)
  File "C:\Users\sofia\Anomaly_detection_poornav\opFlowOfBlocks.py", line 19, in calcOptFlowOfBlocks
    opFlowOfBlocks = np.zeros((xBlockSize,yBlockSize,2))
TypeError: 'float' object cannot be interpreted as an integer

Pl help

**Comment by ayan702** [comment]
ya man same error is coming please help
