### ISSUE TITLE
i used this code in windows with pycharm, could you please tell me how did you calculate the accuracy , by the code or by specific tool, and one more thing < can you upload small video to see the output of this program 

### ISSUE THREAD

**Issue by wassimassi** [Poornav/Unusual-Human-Activity-Detection#4]

**Comment by COULIBALY-Adama** [comment]
Hi,
can you help me
I use the project and I have problems when I execute the code, here is the result

############the result ###########
(py27) C:\Users\PCT517\Documents\Tests\je_tests\New\Unusual-Human-Activity-Detection\code>python training.py
('Training From ', 'videos\\scene1\\train1.avi')
Traceback (most recent call last):
  File "training.py", line 40, in <module>
    train_from_video(video)
  File "training.py", line 19, in train_from_video
    MotionInfOfFrames, rows, cols = mig.getMotionInfuenceMap(vid)
  File "C:\Users\PCT517\Documents\Tests\je_tests\New\Unusual-Human-Activity-Detection\code\motionInfuenceGenerator.py", line 71, in getMotionInfuenceMap
    rows, cols = frame1.shape[0], frame1.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'
#################################

#!/usr/bin/python2 
# -*-coding:Latin-1 -*-
import os, sys

import numpy as np
import motionInfuenceGenerator as mig
import createMegaBlocks as cmb
import cv2

def reject_outliers(data, m=2):
    return data[abs(data - np.mean(data)) < m * np.std(data)]

def train_from_video(vid):
    '''
        calls all methods to train from the given video
        May return codewords or store them.
    '''
    print("Training From ", vid)
    MotionInfOfFrames, rows, cols = mig.getMotionInfuenceMap(vid)
    print("Motion Inf Map", len(MotionInfOfFrames))
    #numpy.save("MotionInfluenceMaps", np.array(MotionInfOfFrames), allow_pickle=True, fix_imports=True)
    megaBlockMotInfVal = cmb.createMegaBlocks(MotionInfOfFrames, rows, cols)
    np.save("videos\scene1\megaBlockMotInfVal_set1_p1_train_40-40_k5.npy",megaBlockMotInfVal)
    print(np.amax(megaBlockMotInfVal))
    print(np.amax(reject_outliers(megaBlockMotInfVal)))
    
    codewords = cmb.kmeans(megaBlockMotInfVal)
    np.save("videos\scene1\codewords_set1_p1_train_40-40_k5.npy",codewords)
    print(codewords)
    return
    
if __name__ == '__main__':
    '''
        defines training set and calls trainFromVideo for every vid
        définit le kit de formation et appelle trainFromVideo pour chaque vidéo 
    '''

    trainingSet = [r"videos\scene1\train1.avi"]
    for video in trainingSet:
        train_from_video(video)
    print("Done")
################################

Help me

**Comment by HempriyaSen** [comment]
I got the same issue but i resolved it by changing the path of the given video

**Comment by harshithtr53** [comment]
Give the full path of the training video.
