### ISSUE TITLE
Error while running the project

### ISSUE THREAD

**Issue by ghost** [Poornav/Unusual-Human-Activity-Detection#9]
Could you tell me why such errors appear?

Traceback (most recent call last):
  File "C:/Users/sergi/PycharmProjects/Unusual-Human-Activity-Detection-master/code/training.py", line 32, in <module>
    train_from_video(video)
  File "C:/Users/sergi/PycharmProjects/Unusual-Human-Activity-Detection-master/code/training.py", line 13, in train_from_video
    MotionInfOfFrames, rows, cols = mig.getMotionInfuenceMap(vid)
  File "C:\Users\sergi\PycharmProjects\Unusual-Human-Activity-Detection-master\code\motionInfuenceGenerator.py", line 64, in getMotionInfuenceMap
    rows, cols = frame1.shape[0], frame1.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by meetvalani** [comment]
That is not the issue. It's just because you have not specified absolute path to video file in file training.py line no 29.

**Comment by ghost** [comment]
Thank you for your reply. I recalled one more question. How many times do I need to train the neural network in order to detect people more accurately?

23 марта 2020, 09:29:57, от "Meet Valani" <notifications@github.com>:



That is not the issue. It's just because you have not specified absolute path to video file in file training.py line no 29.
